title: Wp1998.GitHub.io
description: 
google_analytics: 
show_downloads: true
remote_theme: samarsault/plainwhite-jekyll

gems:
  - jekyll-mentions

plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: samarsault
    github: samarsault
    linkedIn: in/samarsault # format: locale/username
    
    portfolio_image:  "assets/portfolio.png"
    disqus_shortname: games
    sitemap: true
    show_excerpts: true
    navigation:
      - title: My Work
        url: "/my-work"
      - title: Resume
        url: "/resume"
    dark_mode: true
    search: true
