title: Wp1998.GitHub.io
description: 
google_analytics: 
show_downloads: true
remote_theme: samarsault/plainwhite-jekyll

gems:
  - jekyll-mentions

plainwhite:
  name: peng wu
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: wp1998isback
    github: wp1998
    linkedIn: in/wp1998 # format: locale/username
    
    portfolio_image:  "assets/face.jpg"
    disqus_shortname: games
    sitemap: true
    show_excerpts: true
    navigation:
    dark_mode: true
    search: true
